version: 2

jobs:

  build:
    working_directory: ~/function
    docker:
      - image: circleci/node:10.6
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      
      #Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
   
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist


  #The deploy_to_firebase job
  deploy:
    working_directory: ~/src

    docker:
      - image: circleci/node:10.6

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            # Deploy to the S3 bucket corresponding to the current branch
      - run:
          name: Deploy to Firebase
          command: |
                 if [ "${CIRCLE_BRANCH}" == "master" ]; then
                   echo "We don't have production environment"
                 elif [ "${CIRCLE_BRANCH}" =! "master" ]; then
                   ./node_modules/.bin/firebase deploy --only hosting -m INSTA-WEB-PRODUCTION-$(date +%Y%m%d-%H%M) --token=$FIREBASE_DEPLOY_TOKEN
                 fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy